# Metrica

## Available functionality:

- [Load local .json event files](#load-local-files): `metrica.load_event()`

### Load local files

In [5]:
from kloppy import metrica

dataset = metrica.load_event(
    event_data="../../kloppy/tests/files/metrica_events.json",
    meta_data="../../kloppy/tests/files/epts_metrica_metadata.xml",
    
    # Optional arguments
    coordinates="metrica",
    event_types=["shot", "pass"]
)

dataset.to_df().head()

,event_id,event_type,result,success,period_id,timestamp,end_timestamp,ball_state,ball_owning_team,team_id,player_id,coordinates_x,coordinates_y,end_coordinates_x,end_coordinates_y,receiver_player_id,set_piece_type,body_part_type
0,None,PASS,COMPLETE,True,1,14.44,15.08,alive,TEAM_A,TEAM_A,None,0.50125,0.48725,0.49864,0.48705,NaN,KICK_OFF,NaN
1,None,PASS,COMPLETE,True,1,15.36,17.04,alive,TEAM_A,TEAM_A,None,0.49700,0.48500,0.63373,0.63449,NaN,NaN,NaN
2,None,PASS,COMPLETE,True,1,18.60,20.28,alive,TEAM_A,TEAM_A,None,0.66986,0.59707,0.80602,0.39821,NaN,NaN,NaN
3,None,PASS,COMPLETE,True,1,21.20,23.20,alive,TEAM_A,TEAM_A,None,0.80929,0.42922,0.79906,0.81522,NaN,NaN,NaN
4,None,PASS,COMPLETE,True,1,23.92,25.12,alive,TEAM_A,TEAM_A,None,0.79756,0.81998,0.68101,0.98059,NaN,NaN,NaN